version: '2'

services:
    nginx:
        image: nginx:1.11.6-alpine
    postgres:
        image: postgres:9.5.4
        expose:
            - 5432
        volumes:
          - ./docker/postgres/data:/var/lib/postgresql
    django:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
    bind:
        build:
            context: .
            dockerfile: ./docker/bind/Dockerfile
