# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.BooleanField(default=False, help_text='Whether Domains NS record points to our NS', verbose_name='Status of the Domain'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
