# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_record', '0002_auto_20170216_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
