# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dns_record', '0004_auto_20170504_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
